let dados = [
  {
    titulo : "Rebeca Andrade",
    descricao : "Rebeca Rodrigues de Andrade é uma ginasta artística brasileira. Ela é a primeira ginasta brasileira a conquistar uma medalha olímpica na ginástica artística feminina.",
    link : "https://pt.wikipedia.org/wiki/Rebeca_Andrade",
    redeSocial : "https://www.instagram.com/rebecarandrade/",
    tags: "ginasta, ginástica, artística, medalhista, olímpica, brasileira",
  },
  {
    titulo : "Rayssa Leal",
    descricao : "Rayssa Leal, conhecida como a Fadinha do Skate, é uma skatista profissional brasileira. Ela é a mais jovem medalhista olímpica do Brasil, com apenas 13 anos.",
    link : "https://pt.wikipedia.org/wiki/Rayssa_Leal",
    redeSocial : "https://www.instagram.com/rayssalealsk8/",
    tags: "skatista, profissional, medalhista, olímpica, brasileira",
  },
  {
    titulo : "Julia Soares",
    descricao: "Julia Soares é uma jovem ginasta artística brasileira, destaque nas competições internacionais. Com suas apresentações de alto nível e habilidade técnica, ela representa o futuro promissor da ginástica artística do Brasil.",
    link: "https://pt.wikipedia.org/wiki/J%C3%BAlia_Soares",
    redeSocial: "https://www.instagram.com/juju_bsoares/",
    tags: "ginasta, ginástica, artística, brasileira",
  },
  {
    titulo : "Italo Ferreira",
    descricao : "Ítalo Ferreira é um surfista profissional brasileiro. Ele é o primeiro surfista brasileiro a conquistar uma medalha de ouro nas Olimpíadas.",
    link : "https://pt.wikipedia.org/wiki/%C3%8Dtalo_Ferreira",
    redeSocial : "https://www.instagram.com/italoferreira/",
    tags: "surfista, profissional, medalhista, olímpico, brasileiro",
  },
  {
    titulo : "Gabriel Medina",
    descricao : "Gabriel Medina é um surfista profissional brasileiro, bicampeão mundial de surf. Ele é conhecido por seu estilo agressivo e manobras inovadoras nas ondas.",
    link : "https://pt.wikipedia.org/wiki/Gabriel_Medina",
    redeSocial : "https://www.instagram.com/gabrielmedina/",
    tags: "surfista, profissional, bicampeão, mundial, brasileiro",
  },
  {
    titulo : "Ana Marcela Cunha",
    descricao : "Ana Marcela Cunha é uma nadadora de águas abertas brasileira, considerada uma das melhores do mundo em sua modalidade. Ela já conquistou diversos títulos e medalhas em competições internacionais.",
    link : "https://pt.wikipedia.org/wiki/Ana_Marcela_Cunha",
    redeSocial : "https://www.instagram.com/anamarcela92/",
    tags: "nadadora, águas, abertas, brasileira",
  },
 {
    titulo : "Marta",
    descricao : "Marta Vieira da Silva, conhecida como Marta, é uma futebolista brasileira. É amplamente considerada uma das maiores jogadoras de futebol de todos os tempos, eleita seis vezes a Melhor Jogadora do Mundo pela FIFA.",
    link : "https://pt.wikipedia.org/wiki/Marta_(futebolista)",
    redeSocial : "https://www.instagram.com/martavsilva10/",
    tags: "futebolista, futebol, brasileira, melhor do mundo, rainha marta",
  },
  {
    titulo : "Isaquias Queiroz",
    descricao : "Isaquias Queiroz dos Santos é um canoísta brasileiro, o maior medalhista olímpico individual do Brasil. Ele conquistou medalhas em três edições diferentes dos Jogos Olímpicos.",
    link : "https://pt.wikipedia.org/wiki/Isaquias_Queiroz",
    redeSocial : "https://www.instagram.com/isaquias_lx/",
    tags: "canoísta, canoagem, medalhista, olímpico, brasileiro",
  },
  {
    titulo : "Rafaela Silva",
    descricao : "Rafaela Lopes Silva é uma judoca brasileira, campeã olímpica nos Jogos do Rio 2016 e bicampeã mundial de judô na categoria -57 kg. É um dos maiores nomes do judô brasileiro.",
    link : "https://pt.wikipedia.org/wiki/Rafaela_Silva",
    redeSocial : "https://www.instagram.com/rafaelasilva/",
    tags: "judoca, judô, medalhista, olímpica, campeã mundial, brasileira",
  },
  {
    titulo : "César Cielo",
    descricao : "César Augusto Cielo Filho é um nadador brasileiro. É o único campeão olímpico da natação brasileira (Pequim 2008) e multimedalhista em campeonatos mundiais, especialista em provas de velocidade.",
    link : "https://pt.wikipedia.org/wiki/C%C3%A9sar_Cielo",
    redeSocial : "https://www.instagram.com/cesarcielo/",
    tags: "nadador, natação, medalhista, olímpico, campeão mundial, brasileiro, velocidade",
  },
  {
    titulo : "Beatriz Ferreira",
    descricao : "Beatriz Iasmin Soares Ferreira, conhecida como Bia Ferreira, é uma boxeadora brasileira. Ela foi medalhista de prata em Tóquio 2020 e a primeira campeã olímpica do boxe feminino brasileiro em Paris 2024.",
    link : "https://pt.wikipedia.org/wiki/Beatriz_Ferreira",
    redeSocial : "https://www.instagram.com/biabeatrizferreira/",
    tags: "boxeadora, boxe, medalhista, olímpica, campeã olímpica, brasileira",
  },
  {
    titulo : "Neymar",
    descricao : "Neymar da Silva Santos Júnior é um futebolista brasileiro que atua como atacante. É o maior artilheiro da história da Seleção Brasileira e um dos jogadores mais caros da história do futebol.",
    link : "https://pt.wikipedia.org/wiki/Neymar",
    redeSocial : "https://www.instagram.com/neymarjr/",
    tags: "futebolista, futebol, brasileiro, seleção brasileira, atacante",
  },
 {
    titulo : "Vinícius Júnior",
    descricao : "Vinícius José Paixão de Oliveira Júnior, conhecido como Vini Jr., é um futebolista brasileiro que atua como ponta-esquerda. Atualmente joga pelo Real Madrid e é considerado um dos melhores jogadores do mundo.",
    link : "https://pt.wikipedia.org/wiki/Vin%C3%ADcius_J%C3%BAnior",
    redeSocial : "https://www.instagram.com/vinijr/",
    tags: "futebolista, futebol, brasileiro, real madrid, ponta-esquerda",
  },
  {
    titulo : "Daiane dos Santos",
    descricao : "Daiane Garcia dos Santos é uma ex-ginasta artística brasileira, a primeira campeã mundial da ginástica artística brasileira. Ela é conhecida pelos seus movimentos inovadores, como o duplo twist carpado (Dos Santos I).",
    link : "https://pt.wikipedia.org/wiki/Daiane_dos_Santos",
    redeSocial : "https://www.instagram.com/daiane_gs_/",
    tags: "ginasta, ex-ginasta, ginástica, artística, campeã mundial, brasileira",
  },
  {
    titulo : "Ramon Dino",
    descricao : "Ramon Rocha Queiroz, conhecido como Ramon Dino, é um fisiculturista profissional brasileiro. Ele compete na categoria Classic Physique e foi vice-campeão do Mr. Olympia em 2022 e 2023.",
    link : "https://pt.wikipedia.org/wiki/Ramon_Rocha_Queiroz",
    redeSocial : "https://www.instagram.com/ramondinopro/",
    tags: "fisiculturista, bodybuilding, classic physique, mr olympia, brasileiro",
  },
  {
    titulo : "Gustavo Kuerten",
    descricao : "Gustavo Kuerten, o 'Guga', é um ex-tenista profissional brasileiro, ex-número 1 do mundo. Ele é tricampeão de Roland Garros, sendo um dos maiores ídolos do esporte no Brasil.",
    link : "https://pt.wikipedia.org/wiki/Gustavo_Kuerten",
    redeSocial : "https://www.instagram.com/gugakuerten/",
    tags: "tenista, ex-tenista, tênis, número 1, roland garros, brasileiro",
  },
  {
    titulo : "Hortência",
    descricao : "Hortência de Fátima Marcari é uma ex-jogadora de basquetebol brasileira. Considerada a 'Rainha do Basquete', ela é campeã mundial (1994) e medalhista olímpica (prata em 1996).",
    link : "https://pt.wikipedia.org/wiki/Hort%C3%AAncia_Marcari",
    redeSocial : "https://www.instagram.com/hortenciamarcari/",
    tags: "basquetebol, basquete, ex-jogadora, campeã mundial, medalhista, olímpica, brasileira",
  }
];

